### ISSUE TITLE
How to train the existing framework on 100 MRA cases?

### ISSUE THREAD

**Issue by myousefi2016** [fepegar/vesseg#1]
I was able to use your code for segmentation of Circle of Willis in some MRA images, where the result is shown here:

![pic](https://user-images.githubusercontent.com/22246708/64258998-38b25a00-cef6-11e9-92f7-55302628afa9.png)

The results is not that bad but you can see its resolution is not enough for example computational fluid dynamics simulations. I have 100 MRA cases and I wanted to know how can I use a portion of these 100 cases for training your network and use it for the rest of my cases. Any idea how can I modify your code? Any suggestion or recommendation is appreciated.

**Comment by fepegar** [comment]
Hi @myousefi2016, you can train your network using [`NiftyNet`](https://niftynet.io/).
