### ISSUE TITLE
Regarding Dataset

### ISSUE THREAD

**Issue by Svijay98** [fepegar/vesseg#2]
Hi, Could you please share a link to the dataset that you have trained on?

**Comment by fepegar** [comment]
Hi @Svijay98. Unfortunately, I'm not allowed to share the training data.

**Comment by AbadianFatemeh** [comment]
Is there any chance to get the dataset?
Pay for it or buy its license?

**Comment by fepegar** [comment]
No, sorry. It's patient data and needs to be protected. You can find vessel datasets online. The labels we're generated using vesselness filters, thresholding, morphological operations and manual checks. I could share my Master's thesis if you think that'd help.
