### ISSUE TITLE
Weights not available anymore from git-lfs

### ISSUE THREAD

**Issue by mitchazj** [fepegar/vesseg#3]
Hello! I'm trying to download the weights for vesseg, and getting this error:

```
(base) hpc2@ihbi-1953031239l:~/Github$ git clone https://github.com/fepegar/vesseg-models
Cloning into 'vesseg-models'...
remote: Enumerating objects: 14, done.
remote: Total 14 (delta 0), reused 0 (delta 0), pack-reused 14
Unpacking objects: 100% (14/14), 2.80 KiB | 716.00 KiB/s, done.
Downloading models/model_scaling.tar.gz (1.5 MB)
Error downloading object: models/model_scaling.tar.gz (da11775): Smudge error: Error downloading models/model_scaling.tar.gz (da117759610388e74b2e9782fd0b1c3ec2849c54fd4192cf055c2bb49563d947): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

Would it be possible to upload the weights to Google Drive as a backup, or repair the git-lfs setup if the expiration was accidental? :)

**Comment by fepegar** [comment]
Oh, I remember when I used to like Git LFS. I don't really have that file at hand at the moment. Could you please try again on the 1st of November (when the quotas are re-loaded, I think) and let me know if it works? I'll disable LFS.

**Comment by mitchazj** [comment]
Ok, will do. Just made a reminder.

Also as an aside - do you have any documentation on how to train one's own weights?
I have my own data under ethics approval & can spend time labelling as required 😄

**Comment by fepegar** [comment]
I trained using NiftyNet, but it's not maintained anymore. After that, I switched to PyTorch and created [TorchIO](https://torchio.readthedocs.io/). That's what I've been using a lot for the last 1.5 years.

[MONAI](https://docs.monai.io/en/latest/) is "the new NiftyNet". It's still a bit young, but there's a very strong team of developers behind it, and it's meant to have everything you need for a full training pipeline. I don't use it because I like to have some more control of what's going on.

**Comment by mitchazj** [comment]
Just tried again and the quotas aren't working - maybe they haven't refilled yet?

**Comment by fepegar** [comment]
I found this in my settings.

![Screen Shot 2020-11-04 at 16 04 03](https://user-images.githubusercontent.com/12688084/98135187-75d9f980-1eb7-11eb-9aeb-8c26bf0b304a.png)

If you *really* want the weights, I'll pay the $4.50 and upload the files without using LFS. If you're not in such a rush, maybe you can check in exactly 27 days, before my bandwidth is mysteriously emptied...

**Comment by mitchazj** [comment]
If that's possible that would be amazing! I'm mainly just keen to test it and compare results to other methods I'm investigating.

Happy to shout you the $4.50 towards the weights btw (or shout you a coffee if I'm ever around)

**Comment by fepegar** [comment]
No worries. Can you try again?

**Comment by mitchazj** [comment]
That appears to have worked! Thanks a lot, I really appreciate it :)

**Comment by fepegar** [comment]
You're welcome!
