### ISSUE TITLE
Question consultation

### ISSUE THREAD

**Issue by yaolp123** [fepegar/vesseg#4]
Dear authors: 
    Recently I  have a looking at your this project and feel interested in it !  I am interested in this project, but I also face some challenges.  and I wish I could receive your suggestion from your guide.. 
  The question 1 is that, “Brain parcellation performed using GIF, not included in this repository”, but I still not find the related software GIF for this Brain parcellation? 
   The question 2 is that, how could I get the input dataset and the related data label? And I have find that, firstly, the input dataset where vessel datasets online I could find?  For the labels, maybe the labels was made by the vesselness filters, thresholding, morphological operations and manual checks.  what the related software I could implement these functions?
 Any suggestion or recommendation is appreciated.
Thank you. I am looking forward to your reply Sincerely!

Best regards.

**Comment by fepegar** [comment]
Hi @yaolp123,

> The question 1 is that, “Brain parcellation performed using GIF, not included in this repository”, but I still not find the related software GIF for this Brain parcellation?

GIF is included in [NiftySeg](https://github.com/KCL-BMEIS/NiftySeg), but I'd recommend you use more modern tools such as [SynthSeg](https://surfer.nmr.mgh.harvard.edu/fswiki/SynthSeg).

> The question 2 is that, how could I get the input dataset and the related data label? And I have find that, firstly, the input dataset where vessel datasets online I could find? For the labels, maybe the labels was made by the vesselness filters, thresholding, morphological operations and manual checks. what the related software I could implement these functions?

Unfortunately, we're not allowed to share the data we used for training. We used [3D Slicer](https://www.slicer.org/) to manually threshold vesselness-filtered DSA images and some further operations.
